---
- name: java installation
  hosts: localhost
  become: yes
  tasks:
    - name: install java 
      ansible.builtin.apt:
        name: openjdk-17-jdk
        update_cache: yes
        state: present
    - name: unisntall java
      ansible.builtin.apt:
        name: openjdk-17-jdk
        update_cache: yes
        state: absent