---
- name: java installation
  hosts: localhost
  become: yes
  tasks:
    - name: install java 
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
    - name: uninstall java 
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: absent